version: "3.8"
services:

    server:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "zaQ@1234"
            ACCEPT_EULA: "Y"
        ports:
            - "1444:1433"
        volumes:
            - data:/var/opt/mssql

volumes:
  data:
