version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./addon_configuration:/etc/nginx/addon_configuration
      - /etc/letsencrypt:/etc/nginx/letsencrypt
      - ./addon_passwords:/etc/nginx/addon_passwords
      - ./addon_certs:/etc/nginx/addon_certs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
networks:
   webnet:
