version: "3"
services:

  zookeeper:
    image: 'bitnami/zookeeper:3.7.0-debian-10-r177'
    ports:
      - '2181:2181'
    hostname: zookeeper.doitsu.tech
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=changeme

  kafka:
    image: 'bitnami/kafka:3.0.0-debian-10-r1'
    hostname: kafka.doitsu.tech
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:SSL,SSL:SSL,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_SSL_KEYSTORE_FILENAME=kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_CREDENTIALS=changeme
      - KAFKA_CFG_SSL_KEY_CREDENTIALS=changeme
      - KAFKA_CFG_SSL_TRUSTSTORE_FILENAME=kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_CREDENTIALS=changeme

      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=

      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_SECURITY_PROTOCOL=SSL
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=CLIENT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT 
    depends_on:
      - zookeeper
    volumes:
      - './kafka-certs/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks'
      - './kafka-certs/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks'
      # - './secrets/jaas/default.jaas:/opt/bitnami/kafka/config/kafka_jaas.conf'
      # - './secrets/config/:/opt/bitnami/kafka/config/'
    # command:

# volumes:
#   kafka_data:
