version: "3.8"

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=changeme
    networks:
      - network_layer

  kafka1:
    image: "bitnami/kafka:latest"
    hostname: broker1.kafka.cluster
    ports:
      - "19093:9093"
    environment:
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker1.kafka.cluster:9092,CLIENT://broker1.kafka.cluster:9093
      - KAFKA_CERTIFICATE_PASSWORD=changeme
      - KAFKA_CLIENT_USERS=kafka_client
      - KAFKA_CLIENT_PASSWORDS=changeme
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=changeme
    volumes:
      - "./kafka-certs/keystore/broker1.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks"
      - "./kafka-certs/truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks"

      - "./kafka-certs/keystore/producer.keystore.jks:/opt/bitnami/kafka/config/testing/producer.keystore.jks"
      - "./testing-files/client-ssl.properties:/opt/bitnami/kafka/config/client-ssl.properties"
      - "./testing-files/run-test.sh:/opt/bitnami/kafka/run-test.sh"
      # - kafka1_data:/bitnami
    depends_on:
      - zookeeper

    networks:
      - network_layer
  
  # kafka2:
  #   image: "bitnami/kafka:latest"
  #   hostname: broker2.kafka.cluster
  #   ports:
  #     - "29093:9093"
  #   environment:
  #     - KAFKA_CFG_BROKER_ID=1
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
  #     - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker2.kafka.cluster:9092,CLIENT://broker2.kafka.cluster:9093
  #     - KAFKA_CERTIFICATE_PASSWORD=changeme
  #     - KAFKA_CLIENT_USERS=kafka_client
  #     - KAFKA_CLIENT_PASSWORDS=changeme
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ZOOKEEPER_PROTOCOL=SASL
  #     - KAFKA_ZOOKEEPER_USER=kafka
  #     - KAFKA_ZOOKEEPER_PASSWORD=changeme
  #   volumes:
  #     - "./kafka-certs/keystore/broker2.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
  #     - "./kafka-certs/truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
  #     # - kafka2_data:/bitnami
  #   depends_on:
  #     - zookeeper

  #   networks:
  #     - network_layer

  # kafka3:
  #   image: "bitnami/kafka:latest"
  #   hostname: broker3.kafka.cluster
  #   ports:
  #     - "39093:9093"
  #   environment:
  #     - KAFKA_CFG_BROKER_ID=2
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SSL
  #     - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker3.kafka.cluster:9092,CLIENT://broker3.kafka.cluster:9093
  #     - KAFKA_CERTIFICATE_PASSWORD=changeme
  #     - KAFKA_CLIENT_USERS=kafka_client
  #     - KAFKA_CLIENT_PASSWORDS=changeme
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ZOOKEEPER_PROTOCOL=SASL
  #     - KAFKA_ZOOKEEPER_USER=kafka
  #     - KAFKA_ZOOKEEPER_PASSWORD=changeme
  #   volumes:
  #     - "./kafka-certs/keystore/broker3.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
  #     - "./kafka-certs/truststore/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
  #     # - kafka3_data:/bitnami
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - network_layer
# volumes:
# kafka1_data:
# kafka2_data:
# kafka3_data:

networks:
  network_layer:
