version: "3.8"

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2021-11-24T23-19-33Z
  command: server --console-address ":9001" http://minio{1...4}/data
  networks:
    - minio_ingress_network
    - overlay
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: zaQ@1234
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    # command: server /data --console-address ":9001"
    volumes:
      - minio_data1:/data

  minio2:
    <<: *minio-common
    hostname: minio2
    # command: server /data --console-address ":9001"
    volumes:
      - minio_data2:/data

  minio3:
    <<: *minio-common
    hostname: minio3
    # command: server /data --console-address ":9001"
    volumes:
      - minio_data3:/data

  minio4:
    <<: *minio-common
    hostname: minio4
    # command: server /data --console-address ":9001"
    volumes:
      - minio_data4:/data

  minio_ingress:
    image: nginx:1.19.2-alpine
    hostname: minio_ingress
    volumes:
      - ./minio-cluster/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "19000:19000"
      - "19001:19001"
    networks:
      - minio_ingress_network
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio_data1:
  minio_data2:
  minio_data3:
  minio_data4:

networks:
  minio_ingress_network:
    driver: overlay