version: "3.8"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04"
    environment:
        SA_PASSWORD: "zaQ@1234"
        ACCEPT_EULA: "Y"
    ports:
        - "1444:1433"
    volumes:
        - data:/var/opt/mssql
    networks:
      - overlay
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "4.00"
          memory: 2500M

volumes:
  data: