version: '3.8'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888
    networks:
      - kafka

  kafka-ssl-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-ssl-1
    depends_on:
      - zookeeper-1
    ports:
      - "19093:19093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_SSL:SSL,EXTERNAL_SSL:SSL
      KAFKA_LISTENERS: INTERNAL_SSL://kafka-ssl-1:19092,EXTERNAL_SSL://:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_SSL://kafka-ssl-1:19092,EXTERNAL_SSL://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
    volumes:
      - ./secrets:/etc/kafka/secrets
    networks:
      - kafka

networks:
  kafka:
    driver: overlay
    attachable: true

